### ISSUE TITLE
Mux deployment on jboss 7.2 or 7.3

### ISSUE THREAD

**Issue by manaty** [Mobicents/jdiameter#5] opened 2015-10-22 12:17 UTC
When deploying mobicents-diameter-mux-1.6.0.FINAL.sar on jboss 7.2.0final or EAP6.2 we obtain the error :
[2:02:56 PM] Antoine Michéa: Caused by: java.lang.NoClassDefFoundError: org/jboss/system/ServiceMBean
[2:03:01 PM] Antoine Michéa: Caused by: java.lang.ClassNotFoundException: org.jboss.system.ServiceMBean from [Module "deployment.mobicents-diameter-mux-1.6.0.FINAL.sar:main" from Service Module Loader]
        at org.jboss.mod
[2:03:28 PM] Antoine Michéa: pb avec le deploy du dernier sar visiblement
[2:03:50 PM] Antoine Michéa: WARN  [org.jboss.modules] (MSC service thread 1-2) Failed to define class org.mobicents.diameter.stack.DiameterStackMultiplexerMBean in
 Module "deployment.mobicents-diameter-mux-1.6.0.FINAL.sar:main" from Service Module Loader: java.lang.LinkageError: Failed to link org/mobicents/di
ameter/stack/DiameterStackMultiplexerMBean (Module "deployment.mobicents-diameter-mux-1.6.0.FINAL.sar:main" from Service Module Loader)

**Comment by deruelle** [comment] 2015-10-27 17:26
Duplicate of #6

**Closed** 2015-10-30 03:55 UTC
Labels: duplicate
